### ISSUE TITLE
struct error in vmotion cookie handling

### ISSUE THREAD

**Issue by isnotajoke** [pbhenson/vSPC.py#17]
Aug  2 11:29:42 hostname vSPC.py[5615]: Worker exception caught
Aug  2 11:29:42 hostname Traceback (most recent call last):
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 1034, in _queue_run
Aug  2 11:29:42 hostname queue.get()()
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 1145, in <lambda>
Aug  2 11:29:42 hostname self.task_queue.put(lambda: self.new_vm_data(vt))
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 1100, in new_vm_data
Aug  2 11:29:42 hostname neg_done = vt.negotiation_done()
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 330, in negotiation_done
Aug  2 11:29:42 hostname self.process_available()
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 327, in process_available
Aug  2 11:29:42 hostname self.process_rawq()
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 210, in process_rawq
Aug  2 11:29:42 hostname self.option_callback(self.sock, c, NOOPT)
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 469, in _option_callback
Aug  2 11:29:42 hostname getattr(self, meth)(data)
Aug  2 11:29:42 hostname File "/usr/lib64/python2.7/site-packages/vSPC.py", line 400, in _handle_vmotion_begin
Aug  2 11:29:42 hostname cookie = data + struct.pack("i", hash(self) & 0xFFFFFFFF)
Aug  2 11:29:42 hostname error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by xuguanghan** [comment]
change 
cookie = data + struct.pack("i", hash(self) & 0xFFFFFFFF)  
to
cookie = data + struct.pack("l", hash(self) & 0xFFFFFFFF)
can fix this issue.

**Comment by pbhenson** [comment]
Fixed in master.
